import type {
  Correction,
  Day,
  Difficulty,
  Exercise,
  LessonSection,
  QuizQuestion,
  Week,
} from "@/content/week-1";

type ExerciseSeed = {
  letter: string;
  title: string;
  difficulty: Difficulty;
  minutes: number;
  skills: string[];
  statement: string;
  mistakes: string[];
  hints: string[];
  solution: string;
  explanation: string;
  reasoning: string;
};

function lesson(
  id: string,
  title: string,
  content: string,
  exampleCode?: string,
  keyTakeaways: string[] = [],
): LessonSection {
  return { id, title, content, exampleCode, keyTakeaways };
}

function quiz(
  week: number,
  day: number,
  index: number,
  question: string,
  choices: string[],
  answer: number,
  explanation: string,
): QuizQuestion {
  return {
    id: `q-w${week}-d${day}-${index}`,
    question,
    choices,
    answer,
    explanation,
  };
}

function buildDay({
  week,
  dayNumber,
  title,
  theme,
  duration,
  morning,
  exercises,
  quizQuestions,
  revisionPrompts,
  checklist,
}: {
  week: number;
  dayNumber: number;
  title: string;
  theme: string;
  duration: string;
  morning: LessonSection[];
  exercises: ExerciseSeed[];
  quizQuestions: QuizQuestion[];
  revisionPrompts: string[];
  checklist: string[];
}): { day: Day; corrections: Correction[] } {
  const afternoonExercises: Exercise[] = [];
  const corrections: Correction[] = [];

  for (const seed of exercises) {
    const id = `w${week}-d${dayNumber}-${seed.letter.toLowerCase()}`;
    const correctionId = `c-${id}`;
    afternoonExercises.push({
      id,
      title: seed.title,
      day: dayNumber,
      difficulty: seed.difficulty,
      estimatedMinutes: seed.minutes,
      skills: seed.skills,
      statement: seed.statement,
      frequentMistakes: seed.mistakes,
      hints: seed.hints,
      correctionId,
    });
    corrections.push({
      id: correctionId,
      week,
      day: dayNumber,
      exerciseId: id,
      title: seed.title,
      solution: seed.solution,
      explanation: seed.explanation,
      reasoning: seed.reasoning,
      commonTraps: seed.mistakes,
      howToTest: [
        "Lance le script ou la commande avec un cas simple.",
        "Teste un cas limite ou une erreur volontaire.",
        "Explique le résultat avec tes mots.",
      ],
    });
  }

  return {
    day: {
      id: `day-${dayNumber}`,
      week,
      dayNumber,
      title,
      theme,
      duration,
      morning,
      afternoonExercises,
      eveningQuiz: quizQuestions,
      revisionPrompts,
      checklist,
    },
    corrections,
  };
}

const week2Parts = [
  buildDay({
    week: 2,
    dayNumber: 1,
    title: "Fichiers texte",
    theme: "Lire, écrire, ajouter et sécuriser les accès fichier en Python",
    duration: "Matin 2 h · Exercices 2 h · Soir 30 min",
    morning: [
      lesson(
        "w2-d1-files-open",
        "Ouvrir un fichier",
        "Un fichier texte permet de conserver une trace après la fermeture du programme. En Python, on utilise with open(...) pour ouvrir puis refermer proprement.",
        'with open("notes.txt", "r", encoding="utf-8") as fichier:\n    contenu = fichier.read()\nprint(contenu)',
        ["r lit", "w réécrit", "a ajoute", "with referme automatiquement"],
      ),
      lesson(
        "w2-d1-lines",
        "Lire ligne par ligne",
        "Quand un fichier grandit, lire ligne par ligne évite de tout mélanger. Chaque ligne peut ensuite être nettoyée avec strip().",
        'with open("journal.txt", "r", encoding="utf-8") as fichier:\n    for ligne in fichier:\n        print(ligne.strip())',
        ["strip retire les retours à la ligne", "une boucle peut parcourir un fichier"],
      ),
    ],
    exercises: [
      {
        letter: "a",
        title: "Créer un journal",
        difficulty: "facile",
        minutes: 8,
        skills: ["open", "write"],
        statement: "Crée journal.txt et écris une ligne indiquant ce que tu as travaillé aujourd'hui.",
        mistakes: ["Oublier encoding=\"utf-8\".", "Écraser le fichier sans le vouloir."],
        hints: ["Utilise le mode w.", "Écris une chaîne simple.", "Vérifie le fichier après lancement."],
        solution: `with open("journal.txt", "w", encoding="utf-8") as fichier:
    fichier.write("Aujourd'hui : fichiers Python\n")`,
        explanation: "Le mode w crée le fichier ou remplace son contenu. with referme le fichier automatiquement.",
        reasoning: "On commence par une écriture simple pour comprendre le lien entre programme et fichier réel.",
      },
      {
        letter: "b",
        title: "Ajouter sans écraser",
        difficulty: "moyen",
        minutes: 10,
        skills: ["append", "journal"],
        statement: "Ajoute une nouvelle ligne dans journal.txt sans supprimer la ligne précédente.",
        mistakes: ["Utiliser w au lieu de a."],
        hints: ["Le mode ajout est a.", "Ajoute \\n à la fin.", "Relance deux fois pour tester."],
        solution: 'with open("journal.txt", "a", encoding="utf-8") as fichier:\n    fichier.write("Nouvelle session de travail\\n")',
        explanation: "Le mode a place l'écriture à la fin du fichier.",
        reasoning: "Un journal doit garder l'historique, donc on ajoute au lieu de remplacer.",
      },
      {
        letter: "c",
        title: "Compter les lignes",
        difficulty: "moyen",
        minutes: 12,
        skills: ["for", "fichier", "compteur"],
        statement: "Lis journal.txt et affiche combien de lignes il contient.",
        mistakes: ["Compter les caractères au lieu des lignes."],
        hints: ["Initialise compteur = 0.", "Parcours le fichier.", "Ajoute 1 à chaque ligne."],
        solution: 'compteur = 0\nwith open("journal.txt", "r", encoding="utf-8") as fichier:\n    for ligne in fichier:\n        compteur = compteur + 1\nprint(compteur)',
        explanation: "La boucle passe une fois par ligne, donc le compteur mesure bien le nombre de lignes.",
        reasoning: "On réutilise l'accumulateur de la semaine 1, mais appliqué aux fichiers.",
      },
      {
        letter: "d",
        title: "Chercher un mot",
        difficulty: "difficile",
        minutes: 15,
        skills: ["in", "recherche", "strip"],
        statement: "Demande un mot, puis affiche toutes les lignes du journal qui contiennent ce mot.",
        mistakes: ["Comparer la ligne entière au mot.", "Oublier de gérer la casse."],
        hints: ["Utilise in.", "Passe ligne et mot en lower().", "Affiche ligne.strip()."],
        solution: 'mot = input("Mot : ").lower()\nwith open("journal.txt", "r", encoding="utf-8") as fichier:\n    for ligne in fichier:\n        if mot in ligne.lower():\n            print(ligne.strip())',
        explanation: "in vérifie si une chaîne est contenue dans une autre. lower évite les différences de majuscules.",
        reasoning: "Chercher dans un fichier revient à parcourir ses lignes puis filtrer.",
      },
    ],
    quizQuestions: [
      quiz(2, 1, 1, "Quel mode ajoute à la fin d'un fichier ?", ["r", "w", "a"], 2, "a signifie append, donc ajout."),
      quiz(2, 1, 2, "Pourquoi utiliser with open(...) ?", ["Pour fermer automatiquement", "Pour accélérer Python", "Pour créer une boucle"], 0, "with gère la fermeture même en cas d'erreur."),
      quiz(2, 1, 3, "Que fait strip() sur une ligne ?", ["Supprime le fichier", "Nettoie les espaces et retours ligne", "Trie les mots"], 1, "strip nettoie le début et la fin de la chaîne."),
    ],
    revisionPrompts: ["Explique r, w et a.", "Pourquoi un journal utilise plutôt a ?", "Comment compter des lignes ?"],
    checklist: ["Je sais lire un fichier.", "Je sais ajouter sans écraser.", "Je sais parcourir ligne par ligne."],
  }),
  buildDay({
    week: 2,
    dayNumber: 2,
    title: "Listes avancées",
    theme: "Parcourir, filtrer, trier et transformer des collections simples",
    duration: "Matin 2 h · Exercices 2 h · Soir 30 min",
    morning: [
      lesson(
        "w2-d2-list-methods",
        "Méthodes utiles",
        "Une liste peut évoluer : append ajoute, remove retire, sort trie. L'important est de savoir quand on modifie la liste et quand on crée une nouvelle valeur.",
        "notes = [12, 8, 15]\nnotes.append(17)\nnotes.sort()\nprint(notes)",
        ["append ajoute", "sort trie sur place", "len donne la taille"],
      ),
      lesson(
        "w2-d2-filter",
        "Filtrer une liste",
        "Filtrer, c'est construire une nouvelle liste avec seulement les éléments qui respectent une condition.",
        "notes = [8, 12, 15, 7]\nvalides = []\nfor note in notes:\n    if note >= 10:\n        valides.append(note)",
        ["un filtre combine boucle + condition", "append construit le résultat"],
      ),
    ],
    exercises: [
      {
        letter: "a",
        title: "Notes validées",
        difficulty: "facile",
        minutes: 8,
        skills: ["liste", "condition"],
        statement: "À partir de notes = [8, 12, 15, 7, 10], affiche seulement les notes supérieures ou égales à 10.",
        mistakes: ["Modifier la liste pendant le parcours sans raison."],
        hints: ["Parcours chaque note.", "Teste note >= 10.", "Affiche si vrai."],
        solution: "notes = [8, 12, 15, 7, 10]\nfor note in notes:\n    if note >= 10:\n        print(note)",
        explanation: "La condition sélectionne les notes validées.",
        reasoning: "On sépare le parcours de la règle métier : valider à partir de 10.",
      },
      {
        letter: "b",
        title: "Construire une nouvelle liste",
        difficulty: "moyen",
        minutes: 10,
        skills: ["append", "filtre"],
        statement: "Crée une liste admis qui contient uniquement les notes >= 10, puis affiche-la.",
        mistakes: ["Oublier d'initialiser admis = []."],
        hints: ["Crée une liste vide.", "Ajoute avec append.", "Affiche à la fin."],
        solution: "notes = [8, 12, 15, 7, 10]\nadmis = []\nfor note in notes:\n    if note >= 10:\n        admis.append(note)\nprint(admis)",
        explanation: "append ajoute chaque note retenue dans une nouvelle collection.",
        reasoning: "Une nouvelle liste garde le résultat pour un traitement ultérieur.",
      },
      {
        letter: "c",
        title: "Maximum manuel",
        difficulty: "moyen",
        minutes: 12,
        skills: ["maximum", "boucle"],
        statement: "Trouve la plus grande note sans utiliser max().",
        mistakes: ["Initialiser le maximum à 0 sans réfléchir."],
        hints: ["Pars de notes[0].", "Compare chaque note.", "Remplace si plus grand."],
        solution: "notes = [8, 12, 15, 7, 10]\nmeilleure = notes[0]\nfor note in notes[1:]:\n    if note > meilleure:\n        meilleure = note\nprint(meilleure)",
        explanation: "La meilleure valeur provisoire est améliorée au fil du parcours.",
        reasoning: "Cet exercice entraîne le raisonnement d'algorithme, pas seulement l'appel d'une fonction prête.",
      },
      {
        letter: "d",
        title: "Trier puis afficher",
        difficulty: "difficile",
        minutes: 12,
        skills: ["sort", "affichage"],
        statement: "Trie les notes, puis affiche-les une par une avec leur rang.",
        mistakes: ["Croire que sort renvoie une nouvelle liste."],
        hints: ["notes.sort() modifie notes.", "Utilise range(len(notes)).", "Le rang commence à 1."],
        solution: "notes = [8, 12, 15, 7, 10]\nnotes.sort()\nfor i in range(len(notes)):\n    print(i + 1, notes[i])",
        explanation: "sort trie la liste sur place, puis l'index permet d'afficher le rang.",
        reasoning: "On combine transformation de liste et parcours indexé.",
      },
    ],
    quizQuestions: [
      quiz(2, 2, 1, "Quelle méthode ajoute à la fin ?", ["push", "append", "add"], 1, "En Python, c'est append."),
      quiz(2, 2, 2, "Que vaut len([4, 5, 6]) ?", ["2", "3", "6"], 1, "Il y a trois éléments."),
      quiz(2, 2, 3, "sort() renvoie quoi principalement ?", ["Une liste triée nouvelle", "Modifie la liste", "Un texte"], 1, "sort trie sur place."),
    ],
    revisionPrompts: ["Différence entre afficher et stocker ?", "Pourquoi partir de notes[0] pour un maximum ?", "Que fait sort() ?"],
    checklist: ["Je sais filtrer.", "Je sais créer une nouvelle liste.", "Je sais trier et parcourir."],
  }),
  buildDay({
    week: 2,
    dayNumber: 3,
    title: "Dictionnaires",
    theme: "Associer des clés et des valeurs pour représenter des données",
    duration: "Matin 2 h · Exercices 2 h · Soir 30 min",
    morning: [
      lesson(
        "w2-d3-dict",
        "Clés et valeurs",
        "Un dictionnaire associe une clé à une valeur. C'est très pratique pour représenter une personne, une note, un produit ou une ligne de données.",
        'etudiant = {"nom": "Nadia", "moyenne": 14}\nprint(etudiant["nom"])\nprint(etudiant["moyenne"])',
        ["une clé doit exister", "les accolades créent un dictionnaire"],
      ),
      lesson(
        "w2-d3-loop",
        "Parcourir un dictionnaire",
        "items() permet de parcourir les couples clé-valeur.",
        'for cle, valeur in etudiant.items():\n    print(cle, "=", valeur)',
        ["items donne clé et valeur", "un dictionnaire structure les données"],
      ),
    ],
    exercises: [
      {
        letter: "a",
        title: "Carte étudiant",
        difficulty: "facile",
        minutes: 8,
        skills: ["dict", "clé"],
        statement: "Crée un dictionnaire étudiant avec nom, age et groupe, puis affiche chaque information.",
        mistakes: ["Utiliser des index numériques comme dans une liste."],
        hints: ["Utilise des clés textuelles.", "Accède avec etudiant[\"nom\"].", "Affiche trois lignes."],
        solution: 'etudiant = {"nom": "Nadia", "age": 18, "groupe": "A"}\nprint(etudiant["nom"])\nprint(etudiant["age"])\nprint(etudiant["groupe"])',
        explanation: "Chaque clé donne accès à une information précise.",
        reasoning: "Le dictionnaire donne du sens aux données, contrairement à une liste anonyme.",
      },
      {
        letter: "b",
        title: "Ajouter une moyenne",
        difficulty: "moyen",
        minutes: 8,
        skills: ["dict", "affectation"],
        statement: "Ajoute la clé moyenne au dictionnaire étudiant, puis affiche le dictionnaire complet.",
        mistakes: ["Recréer tout le dictionnaire inutilement."],
        hints: ["Une clé peut être ajoutée par affectation.", "Nom du dictionnaire, puis crochets.", "Affiche à la fin."],
        solution: 'etudiant = {"nom": "Nadia", "age": 18, "groupe": "A"}\netudiant["moyenne"] = 14.5\nprint(etudiant)',
        explanation: "Affecter une valeur à une nouvelle clé l'ajoute au dictionnaire.",
        reasoning: "Une structure peut évoluer quand une nouvelle information apparaît.",
      },
      {
        letter: "c",
        title: "Parcours propre",
        difficulty: "moyen",
        minutes: 10,
        skills: ["items", "boucle"],
        statement: "Affiche toutes les clés et valeurs du dictionnaire sous la forme clé : valeur.",
        mistakes: ["Parcourir seulement les clés et oublier les valeurs."],
        hints: ["Utilise items().", "Deux variables dans la boucle.", "Formate avec print."],
        solution: 'etudiant = {"nom": "Nadia", "age": 18, "groupe": "A", "moyenne": 14.5}\nfor cle, valeur in etudiant.items():\n    print(cle, ":", valeur)',
        explanation: "items() fournit directement les couples clé-valeur.",
        reasoning: "C'est la forme la plus lisible pour inspecter un dictionnaire.",
      },
      {
        letter: "d",
        title: "Annuaire simple",
        difficulty: "difficile",
        minutes: 15,
        skills: ["dict", "recherche"],
        statement: "Crée un annuaire prénom -> téléphone. Demande un prénom et affiche le numéro s'il existe.",
        mistakes: ["Accéder directement à une clé qui n'existe pas."],
        hints: ["Utilise if prenom in annuaire.", "Sinon affiche inconnu.", "Teste deux prénoms."],
        solution: 'annuaire = {"Nadia": "0600000001", "Leo": "0600000002"}\nprenom = input("Prénom : ")\nif prenom in annuaire:\n    print(annuaire[prenom])\nelse:\n    print("Inconnu")',
        explanation: "Le test in vérifie la présence de la clé avant l'accès.",
        reasoning: "On évite une erreur en vérifiant d'abord que la donnée existe.",
      },
    ],
    quizQuestions: [
      quiz(2, 3, 1, "Quel symbole crée un dictionnaire ?", ["[]", "{}", "()"], 1, "Les accolades créent le dictionnaire."),
      quiz(2, 3, 2, "Que donne dict.items() ?", ["Les valeurs seules", "Les couples clé-valeur", "La taille"], 1, "items sert à parcourir clés et valeurs."),
      quiz(2, 3, 3, "Pourquoi tester if cle in dict ?", ["Pour éviter une clé absente", "Pour trier", "Pour supprimer"], 0, "Cela évite une erreur d'accès."),
    ],
    revisionPrompts: ["Clé vs valeur ?", "Quand préférer un dictionnaire à une liste ?", "À quoi sert items() ?"],
    checklist: ["Je sais lire une clé.", "Je sais ajouter une entrée.", "Je sais tester l'existence d'une clé."],
  }),
  buildDay({
    week: 2,
    dayNumber: 4,
    title: "Fonctions propres",
    theme: "Découper un programme, nommer clairement et éviter la duplication",
    duration: "Matin 2 h · Exercices 2 h · Soir 30 min",
    morning: [
      lesson(
        "w2-d4-clean-functions",
        "Une fonction = une responsabilité",
        "Une fonction facile à tester fait une seule chose. Son nom doit annoncer son rôle.",
        "def calculer_ttc(prix_ht):\n    return prix_ht * 1.20",
        ["un nom clair aide la lecture", "return facilite les tests"],
      ),
      lesson(
        "w2-d4-main",
        "Point d'entrée main",
        "Regrouper le déroulé principal dans main() rend le fichier plus propre.",
        'def main():\n    print("Programme lancé")\n\nmain()',
        ["main organise", "les fonctions restent au-dessus"],
      ),
    ],
    exercises: [
      {
        letter: "a",
        title: "Prix TTC en fonction",
        difficulty: "facile",
        minutes: 8,
        skills: ["fonction", "return"],
        statement: "Écris calculer_ttc(prix_ht) qui renvoie le prix TTC avec TVA 20%.",
        mistakes: ["Afficher au lieu de renvoyer."],
        hints: ["Paramètre prix_ht.", "Formule prix_ht * 1.20.", "Teste avec print."],
        solution: "def calculer_ttc(prix_ht):\n    return prix_ht * 1.20\n\nprint(calculer_ttc(10))",
        explanation: "La fonction renvoie un résultat réutilisable.",
        reasoning: "On transforme un calcul isolé en brique testable.",
      },
      {
        letter: "b",
        title: "Valider une note",
        difficulty: "moyen",
        minutes: 10,
        skills: ["booléen", "fonction"],
        statement: "Écris note_valide(note) qui renvoie True si la note est entre 0 et 20.",
        mistakes: ["Renvoyer le texte \"True\" au lieu du booléen."],
        hints: ["Utilise and.", "La comparaison renvoie déjà un booléen.", "Teste -1, 12, 25."],
        solution: "def note_valide(note):\n    return note >= 0 and note <= 20\n\nprint(note_valide(12))",
        explanation: "Le résultat de la condition est directement True ou False.",
        reasoning: "Les fonctions booléennes rendent les contrôles plus lisibles.",
      },
      {
        letter: "c",
        title: "Moyenne sécurisée",
        difficulty: "moyen",
        minutes: 12,
        skills: ["liste", "fonction", "cas limite"],
        statement: "Écris moyenne(notes) qui renvoie None si la liste est vide, sinon la moyenne.",
        mistakes: ["Diviser par len(notes) quand la liste est vide."],
        hints: ["Teste d'abord len(notes) == 0.", "Sinon accumule.", "Retourne None pour vide."],
        solution: "def moyenne(notes):\n    if len(notes) == 0:\n        return None\n    total = 0\n    for note in notes:\n        total = total + note\n    return total / len(notes)",
        explanation: "Le cas vide est traité avant la division.",
        reasoning: "Une fonction propre pense aux cas limites avant le cas normal.",
      },
      {
        letter: "d",
        title: "Menu découpé",
        difficulty: "difficile",
        minutes: 18,
        skills: ["main", "menu", "découpage"],
        statement: "Crée un petit menu avec deux fonctions : afficher_menu() et main().",
        mistakes: ["Tout écrire sans découpage."],
        hints: ["afficher_menu ne fait qu'afficher.", "main gère le choix.", "Teste quitter."],
        solution: 'def afficher_menu():\n    print("1 - Dire bonjour")\n    print("2 - Quitter")\n\ndef main():\n    choix = ""\n    while choix != "2":\n        afficher_menu()\n        choix = input("Choix : ")\n        if choix == "1":\n            print("Bonjour")\n\nmain()',
        explanation: "L'affichage et le déroulé principal sont séparés.",
        reasoning: "Cette organisation prépare les projets plus longs.",
      },
    ],
    quizQuestions: [
      quiz(2, 4, 1, "Pourquoi préférer return à print dans un calcul ?", ["Pour réutiliser le résultat", "Pour aller plus vite", "Pour créer un fichier"], 0, "return donne une valeur à réutiliser."),
      quiz(2, 4, 2, "Une fonction propre fait idéalement...", ["tout le programme", "une tâche claire", "aucun test"], 1, "Une responsabilité par fonction."),
      quiz(2, 4, 3, "Pourquoi tester une liste vide ?", ["Pour éviter /0", "Pour trier", "Pour afficher plus vite"], 0, "len(notes) vaut 0, donc division impossible."),
    ],
    revisionPrompts: ["Qu'est-ce qu'une responsabilité ?", "Pourquoi main() aide ?", "Comment tester une fonction ?"],
    checklist: ["Je sais écrire une fonction testable.", "Je sais gérer un cas limite.", "Je sais organiser un menu."],
  }),
  buildDay({
    week: 2,
    dayNumber: 5,
    title: "Git essentiel",
    theme: "Versionner son travail avec init, status, add, commit et log",
    duration: "Matin 2 h · Exercices 2 h · Soir 30 min",
    morning: [
      lesson(
        "w2-d5-git-flow",
        "Le cycle Git",
        "Git garde l'historique de ton projet. Le cycle minimal est : modifier, vérifier, ajouter, committer.",
        "git status\ngit add main.py\ngit commit -m \"Add first script\"\ngit log --oneline",
        ["status montre l'état", "add prépare", "commit enregistre"],
      ),
    ],
    exercises: [
      {
        letter: "a",
        title: "Initialiser un dépôt",
        difficulty: "facile",
        minutes: 8,
        skills: ["git init", "status"],
        statement: "Crée un dossier git-lab, entre dedans, initialise Git et affiche le statut.",
        mistakes: ["Lancer git init dans le mauvais dossier."],
        hints: ["Vérifie pwd.", "Utilise git init.", "Termine par git status."],
        solution: "mkdir git-lab\ncd git-lab\ngit init\ngit status",
        explanation: "git init crée le dépôt dans le dossier courant.",
        reasoning: "On commence par vérifier l'emplacement avant de versionner.",
      },
      {
        letter: "b",
        title: "Premier commit",
        difficulty: "moyen",
        minutes: 12,
        skills: ["add", "commit"],
        statement: "Crée main.py, ajoute-le à Git, puis fais un commit clair.",
        mistakes: ["Commiter sans git add."],
        hints: ["Crée le fichier.", "git add main.py.", "Message court et précis."],
        solution: 'echo "print(\\"Bonjour Git\\")" > main.py\ngit add main.py\ngit commit -m "Add main script"',
        explanation: "add place le fichier dans la zone de préparation, commit enregistre l'état.",
        reasoning: "Un commit doit représenter une étape compréhensible du projet.",
      },
      {
        letter: "c",
        title: "Lire l'historique",
        difficulty: "moyen",
        minutes: 8,
        skills: ["log", "diff"],
        statement: "Modifie main.py, puis observe la différence avant de committer.",
        mistakes: ["Ne jamais regarder ce qui va être enregistré."],
        hints: ["Modifie une ligne.", "git diff.", "Puis add/commit."],
        solution: 'echo "print(\\"Deuxième ligne\\")" >> main.py\ngit diff\ngit add main.py\ngit commit -m "Update main script"\ngit log --oneline',
        explanation: "diff montre les changements non encore commités.",
        reasoning: "Lire son diff évite d'enregistrer des erreurs bêtes.",
      },
      {
        letter: "d",
        title: "Ignorer un fichier",
        difficulty: "difficile",
        minutes: 12,
        skills: [".gitignore", "fichiers temporaires"],
        statement: "Crée un fichier notes.tmp, puis configure .gitignore pour ne pas le versionner.",
        mistakes: ["Ajouter le fichier temporaire avant de l'ignorer."],
        hints: ["Écris *.tmp dans .gitignore.", "Vérifie git status.", "Commit .gitignore."],
        solution: 'echo "brouillon" > notes.tmp\necho "*.tmp" > .gitignore\ngit status\ngit add .gitignore\ngit commit -m "Ignore temporary files"',
        explanation: ".gitignore indique les fichiers que Git doit laisser tranquilles.",
        reasoning: "Un dépôt propre ne contient pas les fichiers temporaires.",
      },
    ],
    quizQuestions: [
      quiz(2, 5, 1, "Quelle commande montre l'état du dépôt ?", ["git status", "git show", "git start"], 0, "status donne l'état courant."),
      quiz(2, 5, 2, "Que fait git add ?", ["Supprime", "Prépare pour commit", "Publie en ligne"], 1, "add prépare les fichiers."),
      quiz(2, 5, 3, "Pourquoi écrire un message de commit clair ?", ["Pour comprendre l'historique", "Pour compiler", "Pour installer Git"], 0, "L'historique doit rester lisible."),
    ],
    revisionPrompts: ["Explique add vs commit.", "À quoi sert git diff ?", "Pourquoi .gitignore ?"],
    checklist: ["Je sais initialiser.", "Je sais faire un commit.", "Je sais lire l'historique."],
  }),
  buildDay({
    week: 2,
    dayNumber: 6,
    title: "Mini-projet données",
    theme: "Construire un gestionnaire de notes avec fichiers, listes, dictionnaires et Git",
    duration: "Projet 3 h · Tests 1 h · Bilan 30 min",
    morning: [
      lesson(
        "w2-d6-project",
        "Assembler les briques",
        "Le projet de semaine 2 combine les fichiers, les listes, les dictionnaires, les fonctions propres et Git.",
        "notes = []\nnotes.append({\"matiere\": \"Algo\", \"note\": 14})",
        ["un projet assemble plusieurs notions", "les données doivent rester lisibles"],
      ),
    ],
    exercises: [
      {
        letter: "a",
        title: "Structure du projet",
        difficulty: "facile",
        minutes: 12,
        skills: ["organisation", "git"],
        statement: "Crée le dossier projet_notes avec main.py, notes.txt et README.md, puis fais un premier commit.",
        mistakes: ["Commencer à coder sans structure."],
        hints: ["Crée les fichiers vides.", "git init.", "Commit de structure."],
        solution: 'mkdir projet_notes\ncd projet_notes\ngit init\ntype nul > main.py\ntype nul > notes.txt\necho "# Projet notes" > README.md\ngit add .\ngit commit -m "Create project structure"',
        explanation: "Une structure claire rend le projet plus simple à faire évoluer.",
        reasoning: "Le premier commit pose un point de départ stable.",
      },
      {
        letter: "b",
        title: "Ajouter une note",
        difficulty: "moyen",
        minutes: 18,
        skills: ["fonction", "fichier"],
        statement: "Écris une fonction ajouter_note() qui demande matière et note puis ajoute une ligne dans notes.txt.",
        mistakes: ["Écraser notes.txt avec w."],
        hints: ["Mode a.", "Sépare matière et note par ;.", "Ajoute un retour ligne."],
        solution: 'def ajouter_note():\n    matiere = input("Matière : ")\n    note = input("Note : ")\n    with open("notes.txt", "a", encoding="utf-8") as fichier:\n        fichier.write(matiere + ";" + note + "\\n")',
        explanation: "Chaque note devient une ligne simple à relire.",
        reasoning: "Un format texte simple suffit pour apprendre la persistance.",
      },
      {
        letter: "c",
        title: "Lire les notes",
        difficulty: "moyen",
        minutes: 18,
        skills: ["split", "liste"],
        statement: "Lis notes.txt et affiche chaque matière avec sa note.",
        mistakes: ["Oublier strip avant split."],
        hints: ["Parcours les lignes.", "strip puis split(';').", "Affiche proprement."],
        solution: 'with open("notes.txt", "r", encoding="utf-8") as fichier:\n    for ligne in fichier:\n        morceaux = ligne.strip().split(";")\n        print(morceaux[0], ":", morceaux[1])',
        explanation: "split découpe chaque ligne selon le séparateur choisi.",
        reasoning: "On transforme une ligne texte en données manipulables.",
      },
      {
        letter: "d",
        title: "Calculer la moyenne",
        difficulty: "difficile",
        minutes: 25,
        skills: ["float", "accumulateur", "fichier"],
        statement: "Calcule la moyenne des notes stockées dans notes.txt.",
        mistakes: ["Additionner des chaînes au lieu de nombres."],
        hints: ["Convertis la note en float.", "Compte les lignes.", "Divise à la fin."],
        solution: 'total = 0\ncompteur = 0\nwith open("notes.txt", "r", encoding="utf-8") as fichier:\n    for ligne in fichier:\n        matiere, note = ligne.strip().split(";")\n        total = total + float(note)\n        compteur = compteur + 1\nif compteur > 0:\n    print(total / compteur)',
        explanation: "Les notes du fichier sont du texte, donc il faut convertir avant le calcul.",
        reasoning: "On retrouve le schéma accumulateur + compteur, appliqué à des données persistées.",
      },
    ],
    quizQuestions: [
      quiz(2, 6, 1, "Quel séparateur est utilisé dans le projet ?", [",", ";", "/"], 1, "Le point-virgule sépare matière et note."),
      quiz(2, 6, 2, "Pourquoi convertir avec float ?", ["Le fichier contient du texte", "Pour trier", "Pour créer Git"], 0, "Une ligne de fichier est lue comme texte."),
      quiz(2, 6, 3, "Quel réflexe avant un gros changement ?", ["Faire un commit propre", "Effacer le projet", "Ignorer Git"], 0, "Un commit stable sécurise le travail."),
    ],
    revisionPrompts: ["Comment stocker une donnée par ligne ?", "Pourquoi split ?", "Quel commit ferais-tu après ajouter_note ?"],
    checklist: ["Je sais créer un projet.", "Je sais persister des notes.", "Je sais calculer depuis un fichier."],
  }),
];

const week3Parts = [
  buildDay({
    week: 3,
    dayNumber: 1,
    title: "SQL et tables",
    theme: "Comprendre tables, lignes, colonnes, clés et requêtes SELECT",
    duration: "Matin 2 h · Exercices 2 h · Soir 30 min",
    morning: [
      lesson(
        "w3-d1-sql-select",
        "Penser en tables",
        "Une base relationnelle range les données dans des tables. Une ligne représente un élément, une colonne une information.",
        "SELECT nom, moyenne\nFROM etudiants\nWHERE moyenne >= 10;",
        ["SELECT choisit les colonnes", "FROM choisit la table", "WHERE filtre les lignes"],
      ),
    ],
    exercises: [
      {
        letter: "a",
        title: "Lire une table",
        difficulty: "facile",
        minutes: 8,
        skills: ["SQL", "SELECT"],
        statement: "Écris une requête qui affiche toutes les colonnes de la table etudiants.",
        mistakes: ["Oublier FROM."],
        hints: ["Toutes les colonnes = *.", "La table est etudiants.", "Termine par ;."],
        solution: "SELECT *\nFROM etudiants;",
        explanation: "SELECT * demande toutes les colonnes de la table.",
        reasoning: "Avant de filtrer, on sait afficher le contenu brut.",
      },
      {
        letter: "b",
        title: "Choisir des colonnes",
        difficulty: "facile",
        minutes: 8,
        skills: ["projection", "SELECT"],
        statement: "Affiche seulement nom et groupe depuis etudiants.",
        mistakes: ["Mettre WHERE à la place de la liste de colonnes."],
        hints: ["Les colonnes se listent après SELECT.", "Sépare par virgule.", "FROM ensuite."],
        solution: "SELECT nom, groupe\nFROM etudiants;",
        explanation: "La projection limite les colonnes visibles.",
        reasoning: "On demande uniquement l'information utile.",
      },
      {
        letter: "c",
        title: "Filtrer les admis",
        difficulty: "moyen",
        minutes: 10,
        skills: ["WHERE", "comparaison"],
        statement: "Affiche les étudiants dont la moyenne est au moins 10.",
        mistakes: ["Utiliser => au lieu de >=."],
        hints: ["Condition dans WHERE.", "Au moins = >=.", "moyenne >= 10."],
        solution: "SELECT nom, moyenne\nFROM etudiants\nWHERE moyenne >= 10;",
        explanation: "WHERE garde seulement les lignes qui respectent la condition.",
        reasoning: "SQL filtre les lignes comme un if filtre des données en Python.",
      },
      {
        letter: "d",
        title: "Trier les résultats",
        difficulty: "moyen",
        minutes: 10,
        skills: ["ORDER BY"],
        statement: "Affiche les étudiants triés par moyenne décroissante.",
        mistakes: ["Croire que DESC est obligatoire partout."],
        hints: ["ORDER BY colonne.", "Décroissant = DESC.", "Place à la fin."],
        solution: "SELECT nom, moyenne\nFROM etudiants\nORDER BY moyenne DESC;",
        explanation: "ORDER BY trie les lignes, DESC met les plus grandes valeurs d'abord.",
        reasoning: "Une requête lisible suit l'ordre SELECT, FROM, WHERE, ORDER BY.",
      },
    ],
    quizQuestions: [
      quiz(3, 1, 1, "Quel mot choisit la table ?", ["SELECT", "FROM", "WHERE"], 1, "FROM indique la table."),
      quiz(3, 1, 2, "Quel mot filtre les lignes ?", ["WHERE", "ORDER", "TABLE"], 0, "WHERE contient la condition."),
      quiz(3, 1, 3, "DESC signifie...", ["croissant", "décroissant", "unique"], 1, "DESC trie du plus grand au plus petit."),
    ],
    revisionPrompts: ["Explique SELECT/FROM/WHERE.", "À quoi sert ORDER BY ?", "SQL filtre-t-il lignes ou colonnes ?"],
    checklist: ["Je sais lire une table.", "Je sais filtrer.", "Je sais trier."],
  }),
  buildDay({
    week: 3,
    dayNumber: 2,
    title: "Modèle relationnel",
    theme: "Clés primaires, clés étrangères et jointures simples",
    duration: "Matin 2 h · Exercices 2 h · Soir 30 min",
    morning: [
      lesson(
        "w3-d2-joins",
        "Relier deux tables",
        "Une clé étrangère relie une ligne à une autre table. JOIN permet de lire les données liées.",
        "SELECT etudiants.nom, groupes.nom\nFROM etudiants\nJOIN groupes ON etudiants.groupe_id = groupes.id;",
        ["id identifie", "clé étrangère relie", "JOIN rassemble"],
      ),
    ],
    exercises: [
      {
        letter: "a",
        title: "Identifier la clé",
        difficulty: "facile",
        minutes: 8,
        skills: ["clé primaire"],
        statement: "Dans une table groupes(id, nom), indique quelle colonne peut servir de clé primaire et pourquoi.",
        mistakes: ["Choisir nom alors qu'il peut changer."],
        hints: ["Une clé primaire identifie une ligne.", "Elle doit être stable.", "id est prévu pour ça."],
        solution: "La clé primaire est id, car elle identifie chaque groupe de façon stable et unique.",
        explanation: "Une clé primaire sert de référence fiable.",
        reasoning: "On évite d'identifier une ligne avec une information qui peut changer.",
      },
      {
        letter: "b",
        title: "Écrire une jointure",
        difficulty: "moyen",
        minutes: 12,
        skills: ["JOIN", "ON"],
        statement: "Écris une requête qui affiche le nom de l'étudiant et le nom de son groupe.",
        mistakes: ["Oublier la condition ON."],
        hints: ["Tables etudiants et groupes.", "Relie groupe_id à id.", "Sélectionne deux noms."],
        solution: "SELECT etudiants.nom, groupes.nom\nFROM etudiants\nJOIN groupes ON etudiants.groupe_id = groupes.id;",
        explanation: "JOIN relie chaque étudiant à son groupe via la clé étrangère.",
        reasoning: "La jointure évite de dupliquer le nom du groupe dans chaque ligne étudiant.",
      },
      {
        letter: "c",
        title: "Filtrer après jointure",
        difficulty: "moyen",
        minutes: 12,
        skills: ["JOIN", "WHERE"],
        statement: "Affiche les étudiants du groupe A uniquement.",
        mistakes: ["Filtrer sur la mauvaise colonne nom."],
        hints: ["Fais d'abord le JOIN.", "Puis WHERE groupes.nom = 'A'.", "Garde les colonnes utiles."],
        solution: "SELECT etudiants.nom\nFROM etudiants\nJOIN groupes ON etudiants.groupe_id = groupes.id\nWHERE groupes.nom = 'A';",
        explanation: "Le filtre peut utiliser une colonne de la table jointe.",
        reasoning: "Après la jointure, les colonnes des deux tables sont disponibles.",
      },
      {
        letter: "d",
        title: "Dessiner le modèle",
        difficulty: "difficile",
        minutes: 15,
        skills: ["MCD", "relation"],
        statement: "Dessine le lien entre etudiants et groupes avec les colonnes id et groupe_id.",
        mistakes: ["Mettre groupe_id dans la table groupes."],
        hints: ["Un étudiant appartient à un groupe.", "La clé étrangère est côté étudiant.", "Relie etudiants.groupe_id vers groupes.id."],
        solution: "groupes(id, nom) 1 --- n etudiants(id, nom, groupe_id). La colonne etudiants.groupe_id référence groupes.id.",
        explanation: "Plusieurs étudiants peuvent pointer vers le même groupe.",
        reasoning: "Le dessin rend visible la cardinalité avant d'écrire les requêtes.",
      },
    ],
    quizQuestions: [
      quiz(3, 2, 1, "Une clé primaire doit être...", ["unique", "longue", "un texte"], 0, "Elle identifie une ligne."),
      quiz(3, 2, 2, "JOIN sert à...", ["supprimer", "relier des tables", "créer Python"], 1, "JOIN combine des tables liées."),
      quiz(3, 2, 3, "ON contient...", ["la condition de liaison", "la liste des colonnes", "le tri"], 0, "ON explique comment relier les tables."),
    ],
    revisionPrompts: ["Clé primaire vs clé étrangère ?", "Pourquoi éviter la duplication ?", "Où se place ON ?"],
    checklist: ["Je sais reconnaître une clé.", "Je sais écrire un JOIN.", "Je sais lire une relation simple."],
  }),
  buildDay({
    week: 3,
    dayNumber: 3,
    title: "Web HTML CSS",
    theme: "Créer une page simple, lisible et structurée",
    duration: "Matin 2 h · Exercices 2 h · Soir 30 min",
    morning: [
      lesson(
        "w3-d3-html",
        "Structure HTML",
        "HTML donne le sens du contenu : titres, paragraphes, listes, liens. CSS gère l'apparence.",
        "<main>\n  <h1>Portfolio</h1>\n  <p>Présentation courte.</p>\n</main>",
        ["HTML structure", "CSS habille", "un h1 par page"],
      ),
    ],
    exercises: [
      {
        letter: "a",
        title: "Page profil",
        difficulty: "facile",
        minutes: 12,
        skills: ["HTML", "structure"],
        statement: "Crée index.html avec un titre, un paragraphe de présentation et une liste de compétences.",
        mistakes: ["Tout mettre dans des div sans titres."],
        hints: ["Utilise h1.", "Une liste = ul/li.", "Mets le contenu dans main."],
        solution: "<main>\n  <h1>Mon profil</h1>\n  <p>Étudiant en préparation BUT Info.</p>\n  <ul>\n    <li>Python</li>\n    <li>Linux</li>\n  </ul>\n</main>",
        explanation: "Les balises donnent une structure claire au contenu.",
        reasoning: "Une page accessible commence par une hiérarchie simple.",
      },
      {
        letter: "b",
        title: "Style lisible",
        difficulty: "moyen",
        minutes: 12,
        skills: ["CSS", "lisibilité"],
        statement: "Ajoute un fichier style.css pour limiter la largeur, aérer le texte et colorer les titres.",
        mistakes: ["Mettre des tailles énormes partout."],
        hints: ["body max-width.", "line-height.", "couleur sobre."],
        solution: "body {\n  max-width: 760px;\n  margin: 40px auto;\n  font-family: Arial, sans-serif;\n  line-height: 1.6;\n}\nh1 { color: #0f766e; }",
        explanation: "Quelques règles suffisent pour rendre la lecture agréable.",
        reasoning: "Le style sert la compréhension, pas la décoration gratuite.",
      },
      {
        letter: "c",
        title: "Lien entre HTML et CSS",
        difficulty: "moyen",
        minutes: 8,
        skills: ["link", "CSS"],
        statement: "Relie style.css à index.html.",
        mistakes: ["Mettre link dans body."],
        hints: ["La balise link va dans head.", "rel=\"stylesheet\".", "href pointe vers le fichier."],
        solution: '<head>\n  <meta charset="utf-8">\n  <link rel="stylesheet" href="style.css">\n  <title>Profil</title>\n</head>',
        explanation: "Le navigateur charge le CSS grâce à la balise link.",
        reasoning: "Séparer contenu et style rend le projet plus propre.",
      },
      {
        letter: "d",
        title: "Carte projet",
        difficulty: "difficile",
        minutes: 18,
        skills: ["HTML", "CSS", "composant"],
        statement: "Crée une carte visuelle présentant le mini-projet de semaine 2.",
        mistakes: ["Rendre la carte illisible sur petit écran."],
        hints: ["Une section avec h2 et p.", "Bordure et padding.", "Largeur fluide."],
        solution: '<section class="card">\n  <h2>Gestionnaire de notes</h2>\n  <p>Un menu pour ajouter, lire et calculer des notes.</p>\n</section>\n\n.card {\n  border: 1px solid #d8e1d7;\n  border-radius: 12px;\n  padding: 16px;\n}',
        explanation: "Une carte regroupe une information courte dans un bloc scannable.",
        reasoning: "On réutilise les principes UX déjà appliqués au site.",
      },
    ],
    quizQuestions: [
      quiz(3, 3, 1, "HTML sert surtout à...", ["structurer", "calculer", "versionner"], 0, "HTML structure le contenu."),
      quiz(3, 3, 2, "CSS sert surtout à...", ["styler", "requêter", "compiler"], 0, "CSS gère l'apparence."),
      quiz(3, 3, 3, "Où placer link rel=stylesheet ?", ["head", "main", "footer"], 0, "Le lien CSS se place dans head."),
    ],
    revisionPrompts: ["HTML vs CSS ?", "Pourquoi une hiérarchie de titres ?", "Qu'est-ce qu'une carte lisible ?"],
    checklist: ["Je sais créer une page.", "Je sais relier un CSS.", "Je sais rendre un bloc lisible."],
  }),
  buildDay({
    week: 3,
    dayNumber: 4,
    title: "JavaScript DOM",
    theme: "Rendre une page interactive avec événements et sélection d'éléments",
    duration: "Matin 2 h · Exercices 2 h · Soir 30 min",
    morning: [
      lesson(
        "w3-d4-dom",
        "Sélectionner et réagir",
        "Le DOM est la représentation de la page dans le navigateur. JavaScript peut sélectionner un élément et réagir à un clic.",
        'const bouton = document.querySelector("button");\nbouton.addEventListener("click", () => {\n  alert("Bonjour");\n});',
        ["querySelector sélectionne", "addEventListener réagit", "un événement déclenche du code"],
      ),
    ],
    exercises: [
      {
        letter: "a",
        title: "Compteur de clics",
        difficulty: "facile",
        minutes: 12,
        skills: ["DOM", "event"],
        statement: "Crée un bouton qui augmente un compteur affiché dans la page.",
        mistakes: ["Oublier de mettre à jour le texte affiché."],
        hints: ["Variable compteur.", "addEventListener click.", "textContent."],
        solution: 'let compteur = 0;\nconst bouton = document.querySelector("#plus");\nconst sortie = document.querySelector("#compteur");\nbouton.addEventListener("click", () => {\n  compteur = compteur + 1;\n  sortie.textContent = compteur;\n});',
        explanation: "Le clic modifie la variable puis l'affichage.",
        reasoning: "Une interaction relie état interne et contenu visible.",
      },
      {
        letter: "b",
        title: "Message personnalisé",
        difficulty: "moyen",
        minutes: 12,
        skills: ["input", "DOM"],
        statement: "Lis un prénom dans un input et affiche Bonjour prénom.",
        mistakes: ["Lire value avant le clic seulement."],
        hints: ["Lis input.value dans l'événement.", "Affiche dans une balise p.", "Teste vide et rempli."],
        solution: 'const input = document.querySelector("#prenom");\nconst sortie = document.querySelector("#message");\ndocument.querySelector("#valider").addEventListener("click", () => {\n  sortie.textContent = "Bonjour " + input.value;\n});',
        explanation: "La valeur doit être lue au moment où l'utilisateur clique.",
        reasoning: "Le DOM permet de récupérer une saisie utilisateur côté navigateur.",
      },
      {
        letter: "c",
        title: "Liste dynamique",
        difficulty: "moyen",
        minutes: 15,
        skills: ["createElement", "append"],
        statement: "Ajoute une tâche dans une liste à chaque clic.",
        mistakes: ["Remplacer toute la liste à chaque fois."],
        hints: ["Crée li.", "li.textContent = input.value.", "ul.append(li)."],
        solution: 'const input = document.querySelector("#tache");\nconst liste = document.querySelector("#liste");\ndocument.querySelector("#ajouter").addEventListener("click", () => {\n  const li = document.createElement("li");\n  li.textContent = input.value;\n  liste.append(li);\n});',
        explanation: "createElement crée un nouvel élément et append l'ajoute à la page.",
        reasoning: "On construit l'interface progressivement selon les actions de l'utilisateur.",
      },
      {
        letter: "d",
        title: "Validation simple",
        difficulty: "difficile",
        minutes: 18,
        skills: ["condition", "DOM"],
        statement: "Empêche l'ajout d'une tâche vide et affiche un message d'erreur.",
        mistakes: ["Comparer sans trim()."],
        hints: ["input.value.trim().", "Si vide, message.", "Sinon ajoute."],
        solution: 'const texte = input.value.trim();\nif (texte === "") {\n  erreur.textContent = "Tâche obligatoire";\n} else {\n  erreur.textContent = "";\n  const li = document.createElement("li");\n  li.textContent = texte;\n  liste.append(li);\n}',
        explanation: "trim évite qu'un champ rempli d'espaces soit accepté.",
        reasoning: "Toute interface doit gérer les mauvaises saisies simplement.",
      },
    ],
    quizQuestions: [
      quiz(3, 4, 1, "querySelector sert à...", ["sélectionner un élément", "trier SQL", "faire un commit"], 0, "Il sélectionne dans le DOM."),
      quiz(3, 4, 2, "Un événement click se gère avec...", ["addEventListener", "SELECT", "git add"], 0, "addEventListener attache une réaction."),
      quiz(3, 4, 3, "textContent modifie...", ["le texte visible", "le fichier Git", "la base SQL"], 0, "Il change le texte d'un élément."),
    ],
    revisionPrompts: ["Qu'est-ce que le DOM ?", "Quand lire input.value ?", "Pourquoi valider une saisie ?"],
    checklist: ["Je sais sélectionner.", "Je sais réagir à un clic.", "Je sais modifier la page."],
  }),
  buildDay({
    week: 3,
    dayNumber: 5,
    title: "Réseau et sécurité",
    theme: "Comprendre client, serveur, HTTP et réflexes de sécurité de base",
    duration: "Matin 2 h · Exercices 2 h · Soir 30 min",
    morning: [
      lesson(
        "w3-d5-http",
        "Client, serveur, requête",
        "Un navigateur est un client. Il envoie une requête HTTP à un serveur, qui renvoie une réponse.",
        "GET /index.html HTTP/1.1\nHost: exemple.test",
        ["client demande", "serveur répond", "HTTP organise l'échange"],
      ),
      lesson(
        "w3-d5-security",
        "Premiers réflexes sécurité",
        "Ne jamais stocker un mot de passe en clair, ne jamais exposer une clé secrète côté client, et valider les entrées utilisateur.",
        undefined,
        ["secret côté serveur", "validation systématique", "messages d'erreur sobres"],
      ),
    ],
    exercises: [
      {
        letter: "a",
        title: "Schéma client serveur",
        difficulty: "facile",
        minutes: 8,
        skills: ["réseau", "HTTP"],
        statement: "Dessine le trajet navigateur -> serveur -> réponse HTML en trois flèches.",
        mistakes: ["Confondre navigateur et serveur."],
        hints: ["Le navigateur demande.", "Le serveur traite.", "Le navigateur affiche."],
        solution: "Navigateur --requête HTTP--> Serveur --réponse HTML/CSS/JS--> Navigateur --affichage--> Utilisateur",
        explanation: "Le navigateur ne possède pas tout : il demande des ressources au serveur.",
        reasoning: "Le schéma clarifie qui fait quoi dans une application web.",
      },
      {
        letter: "b",
        title: "Méthodes HTTP",
        difficulty: "moyen",
        minutes: 10,
        skills: ["GET", "POST"],
        statement: "Explique la différence entre GET et POST avec un exemple de site.",
        mistakes: ["Dire que POST est toujours sécurisé par magie."],
        hints: ["GET lit.", "POST envoie une donnée.", "HTTPS reste nécessaire."],
        solution: "GET sert à demander une ressource, par exemple afficher une page. POST sert à envoyer des données, par exemple un formulaire de connexion. POST ne remplace pas HTTPS.",
        explanation: "Les méthodes indiquent l'intention de la requête.",
        reasoning: "Comprendre HTTP aide à comprendre les formulaires, API et erreurs web.",
      },
      {
        letter: "c",
        title: "Repérer un secret exposé",
        difficulty: "moyen",
        minutes: 10,
        skills: ["sécurité", "secret"],
        statement: "Liste trois informations à ne pas mettre dans du JavaScript public.",
        mistakes: ["Croire qu'un fichier minifié cache un secret."],
        hints: ["Pense mot de passe.", "Pense clé privée.", "Pense token admin."],
        solution: "Ne pas exposer : mot de passe, clé privée, token admin ou clé API secrète. Tout JS envoyé au navigateur peut être lu.",
        explanation: "Le code client est accessible à l'utilisateur.",
        reasoning: "La sécurité commence par savoir où placer les secrets.",
      },
      {
        letter: "d",
        title: "Valider une entrée",
        difficulty: "difficile",
        minutes: 15,
        skills: ["validation", "sécurité"],
        statement: "Écris une règle simple pour refuser un pseudo vide ou trop long.",
        mistakes: ["Valider seulement côté interface et jamais côté serveur."],
        hints: ["trim.", "longueur minimale.", "longueur maximale."],
        solution: "pseudo = pseudo.strip()\nif len(pseudo) == 0 or len(pseudo) > 30:\n    print(\"Pseudo invalide\")",
        explanation: "La validation élimine les entrées vides et limite les abus simples.",
        reasoning: "Toute donnée saisie doit être considérée comme incertaine.",
      },
    ],
    quizQuestions: [
      quiz(3, 5, 1, "Le navigateur est...", ["client", "serveur", "base"], 0, "Il demande des ressources."),
      quiz(3, 5, 2, "POST sert souvent à...", ["envoyer des données", "trier", "committer"], 0, "POST transporte des données de formulaire ou API."),
      quiz(3, 5, 3, "Un secret dans le JS public est...", ["lisible", "invisible", "chiffré automatiquement"], 0, "Le navigateur reçoit ce code."),
    ],
    revisionPrompts: ["Client vs serveur ?", "GET vs POST ?", "Pourquoi valider les entrées ?"],
    checklist: ["Je sais expliquer HTTP.", "Je sais citer des secrets à protéger.", "Je sais proposer une validation simple."],
  }),
  buildDay({
    week: 3,
    dayNumber: 6,
    title: "Mini-projet web",
    theme: "Créer une page de révision interactive connectée aux notions SQL, web et sécurité",
    duration: "Projet 3 h · Tests 1 h · Bilan 30 min",
    morning: [
      lesson(
        "w3-d6-project",
        "Un outil web utile",
        "Le mini-projet de semaine 3 est une page interactive de suivi de révision : HTML/CSS pour la structure, JS pour l'ajout dynamique, et réflexion sécurité sur les entrées.",
        undefined,
        ["interface simple", "interaction courte", "validation visible"],
      ),
    ],
    exercises: [
      {
        letter: "a",
        title: "Structure web",
        difficulty: "facile",
        minutes: 15,
        skills: ["HTML", "organisation"],
        statement: "Crée un projet revision-web avec index.html, style.css et app.js.",
        mistakes: ["Tout mettre dans un seul fichier sans nécessité."],
        hints: ["Trois fichiers.", "Relie CSS et JS.", "Titre clair."],
        solution: "revision-web/\n├── index.html\n├── style.css\n└── app.js",
        explanation: "Séparer structure, style et comportement rend le projet plus lisible.",
        reasoning: "C'est le même réflexe que découper un programme Python.",
      },
      {
        letter: "b",
        title: "Ajouter une notion",
        difficulty: "moyen",
        minutes: 20,
        skills: ["DOM", "liste"],
        statement: "Ajoute une notion de révision dans une liste depuis un input.",
        mistakes: ["Accepter les champs vides."],
        hints: ["input.value.trim().", "createElement.", "append."],
        solution: 'const input = document.querySelector("#notion");\nconst liste = document.querySelector("#liste");\ndocument.querySelector("#ajouter").addEventListener("click", () => {\n  const texte = input.value.trim();\n  if (texte !== "") {\n    const li = document.createElement("li");\n    li.textContent = texte;\n    liste.append(li);\n  }\n});',
        explanation: "On lit la saisie, on valide, puis on crée un élément visible.",
        reasoning: "Le projet relie interaction et validation de base.",
      },
      {
        letter: "c",
        title: "Compter les notions",
        difficulty: "moyen",
        minutes: 15,
        skills: ["compteur", "DOM"],
        statement: "Affiche le nombre de notions ajoutées.",
        mistakes: ["Compter une variable mais oublier l'affichage."],
        hints: ["Variable compteur.", "Incrémente après ajout.", "Met à jour textContent."],
        solution: 'let compteur = 0;\n// après ajout réussi :\ncompteur = compteur + 1;\ndocument.querySelector("#total").textContent = compteur;',
        explanation: "Le compteur est l'état interne, l'élément total est l'état visible.",
        reasoning: "Toute interface interactive synchronise données et affichage.",
      },
      {
        letter: "d",
        title: "Bilan sécurité",
        difficulty: "difficile",
        minutes: 20,
        skills: ["sécurité", "revue"],
        statement: "Écris dans README.md trois limites de sécurité de ton projet et comment tu les améliorerais.",
        mistakes: ["Dire seulement 'c'est sécurisé' sans argument."],
        hints: ["Entrées utilisateur.", "Stockage local.", "Pas de serveur.", "Pas de comptes."],
        solution: "- Les entrées sont seulement validées côté navigateur.\n- Les données ne sont pas sauvegardées sur un serveur.\n- Il n'y a pas d'authentification.\nAméliorations : validation serveur, base de données, comptes utilisateurs.",
        explanation: "Nommer les limites est un vrai réflexe d'informatique.",
        reasoning: "La sécurité se pense aussi quand le projet est petit.",
      },
    ],
    quizQuestions: [
      quiz(3, 6, 1, "Quel fichier contient le comportement ?", ["app.js", "style.css", "README.md"], 0, "Le JavaScript porte l'interaction."),
      quiz(3, 6, 2, "Pourquoi écrire un README ?", ["Pour expliquer le projet", "Pour compiler", "Pour remplacer le CSS"], 0, "README décrit usage et limites."),
      quiz(3, 6, 3, "Une validation côté navigateur suffit-elle toujours ?", ["Non", "Oui", "Seulement en CSS"], 0, "Une vraie application valide aussi côté serveur."),
    ],
    revisionPrompts: ["Comment organiser un projet web ?", "Quelles limites sécurité citer ?", "Que tester avant rendu ?"],
    checklist: ["Je sais créer une page interactive.", "Je sais valider une saisie.", "Je sais expliquer les limites du projet."],
  }),
];

function collect(parts: Array<{ day: Day; corrections: Correction[] }>) {
  return {
    days: parts.map((part) => part.day),
    corrections: parts.flatMap((part) => part.corrections),
  };
}

const week2Collected = collect(week2Parts);
const week3Collected = collect(week3Parts);

export const week2: Week = {
  id: "week-2",
  weekNumber: 2,
  title: "Données, fichiers et Git",
  subtitle: "Tu passes des scripts isolés à des petits programmes organisés, persistants et versionnés.",
  objectives: [
    "Lire et écrire des fichiers texte sans écraser par erreur.",
    "Manipuler listes et dictionnaires pour structurer des données.",
    "Découper un programme avec des fonctions propres.",
    "Versionner un projet avec les commandes Git essentielles.",
    "Construire un mini-projet de gestion de notes.",
  ],
  overview:
    "Cette semaine transforme les bases Python en outils concrets : fichiers, collections, fonctions propres, Git et mini-projet.",
  schedule: [
    { block: "Jour 1", theme: "Fichiers texte", duration: "2 h 30" },
    { block: "Jour 2", theme: "Listes avancées", duration: "2 h 30" },
    { block: "Jour 3", theme: "Dictionnaires", duration: "2 h 30" },
    { block: "Jour 4", theme: "Fonctions propres", duration: "2 h 30" },
    { block: "Jour 5", theme: "Git essentiel", duration: "2 h 30" },
    { block: "Jour 6", theme: "Mini-projet données", duration: "3 h" },
  ],
  targetLevel: [
    "Je sais conserver une donnée dans un fichier.",
    "Je sais choisir entre liste et dictionnaire.",
    "Je sais écrire une fonction testable.",
    "Je sais faire des commits propres.",
    "Je peux expliquer un mini-projet ligne par ligne.",
  ],
  days: week2Collected.days,
  corrections: week2Collected.corrections,
  project: {
    id: "project-week-2",
    title: "Gestionnaire de notes",
    brief: "Créer un programme console qui ajoute, lit et calcule des notes stockées dans un fichier texte.",
    requiredFeatures: [
      "Menu principal avec ajouter, afficher, moyenne et quitter.",
      "Stockage dans notes.txt avec une ligne par note.",
      "Lecture du fichier et affichage lisible.",
      "Calcul de moyenne avec conversion float.",
      "Historique Git avec plusieurs commits clairs.",
    ],
    bonusFeatures: [
      "Filtrer par matière.",
      "Refuser les notes hors 0-20.",
      "Afficher la meilleure note.",
      "Documenter le format du fichier dans README.md.",
    ],
    fileStructure: "projet_notes/\n├── main.py\n├── notes.txt\n└── README.md",
    steps: [
      "Créer la structure et le dépôt Git.",
      "Coder ajouter_note puis committer.",
      "Coder afficher_notes puis committer.",
      "Coder calculer_moyenne puis tester.",
      "Nettoyer les noms et documenter.",
    ],
    successCriteria: [
      "Le menu fonctionne.",
      "Les notes restent après fermeture.",
      "La moyenne est correcte.",
      "Le fichier n'est pas écrasé.",
      "L'historique Git est lisible.",
    ],
    grading: [
      { criterion: "Menu", points: 4 },
      { criterion: "Fichier", points: 4 },
      { criterion: "Moyenne", points: 4 },
      { criterion: "Fonctions", points: 4 },
      { criterion: "Git + README", points: 4 },
    ],
    solution:
      'def ajouter_note():\n    matiere = input("Matière : ")\n    note = input("Note : ")\n    with open("notes.txt", "a", encoding="utf-8") as fichier:\n        fichier.write(matiere + ";" + note + "\\n")\n\n\ndef afficher_notes():\n    with open("notes.txt", "r", encoding="utf-8") as fichier:\n        for ligne in fichier:\n            matiere, note = ligne.strip().split(";")\n            print(matiere, ":", note)\n\n\ndef moyenne():\n    total = 0\n    compteur = 0\n    with open("notes.txt", "r", encoding="utf-8") as fichier:\n        for ligne in fichier:\n            matiere, note = ligne.strip().split(";")\n            total = total + float(note)\n            compteur = compteur + 1\n    if compteur > 0:\n        print(total / compteur)\n\n\nchoix = ""\nwhile choix != "4":\n    print("1 - Ajouter")\n    print("2 - Afficher")\n    print("3 - Moyenne")\n    print("4 - Quitter")\n    choix = input("Choix : ")\n    if choix == "1":\n        ajouter_note()\n    elif choix == "2":\n        afficher_notes()\n    elif choix == "3":\n        moyenne()',
  },
  checkpoint: {
    id: "checkpoint-week-2",
    title: "Bilan semaine 2 - Fichiers, données et Git",
    duration: "1 h 30",
    totalPoints: 100,
    tasks: [
      { id: "w2-cp-files", block: "Fichiers", title: "Journal", points: 20, statement: "Écris puis relis trois lignes dans un fichier journal.txt." },
      { id: "w2-cp-lists", block: "Listes", title: "Filtrer", points: 20, statement: "À partir d'une liste de notes, construis la liste des notes >= 10." },
      { id: "w2-cp-dict", block: "Dictionnaires", title: "Annuaire", points: 20, statement: "Crée un dictionnaire prénom -> téléphone et recherche un prénom." },
      { id: "w2-cp-functions", block: "Fonctions", title: "Moyenne sûre", points: 20, statement: "Écris moyenne(notes) qui gère la liste vide." },
      { id: "w2-cp-git", block: "Git", title: "Historique", points: 20, statement: "Explique status, add, commit et log avec une phrase chacun." },
    ],
    passCriteria: ["70 points ou plus.", "Aucun bloc fondamental à zéro.", "Projet notes rendu et testé."],
    reviewAdvice: [
      { if: "Tu bloques sur fichiers", then: "Refais jour 1 avec un fichier minuscule." },
      { if: "Tu bloques sur Git", then: "Refais init/add/commit/log dans un dossier test." },
    ],
  },
  sheets: [
    { id: "w2-sheet-files", title: "Fichiers Python", items: ["r lit", "w remplace", "a ajoute", "with open referme automatiquement"] },
    { id: "w2-sheet-git", title: "Git minimal", items: ["git status", "git add fichier", "git commit -m message", "git log --oneline"] },
  ],
  revisionCards: [
    { id: "w2-card-open", title: "Mode fichier", front: "Quel mode ajoute sans écraser ?", back: "Le mode a.", skill: "fichiers" },
    { id: "w2-card-dict", title: "Dictionnaire", front: "Comment tester si une clé existe ?", back: "Avec if cle in dictionnaire.", skill: "dictionnaires" },
    { id: "w2-card-git", title: "Git", front: "Différence entre add et commit ?", back: "add prépare, commit enregistre.", skill: "git" },
  ],
};

export const week3: Week = {
  id: "week-3",
  weekNumber: 3,
  title: "SQL, web et sécurité",
  subtitle: "Tu découvres les bases de données, le web interactif et les premiers réflexes de sécurité.",
  objectives: [
    "Lire et filtrer des données avec SQL.",
    "Comprendre les relations entre tables.",
    "Créer une page HTML/CSS lisible.",
    "Ajouter de petites interactions JavaScript.",
    "Expliquer client, serveur, HTTP et validation.",
  ],
  overview:
    "Cette semaine ouvre vers les notions BUT très visibles : SQL, modèle relationnel, web, DOM, réseau et sécurité.",
  schedule: [
    { block: "Jour 1", theme: "SQL SELECT", duration: "2 h 30" },
    { block: "Jour 2", theme: "Relations et JOIN", duration: "2 h 30" },
    { block: "Jour 3", theme: "HTML CSS", duration: "2 h 30" },
    { block: "Jour 4", theme: "JavaScript DOM", duration: "2 h 30" },
    { block: "Jour 5", theme: "Réseau et sécurité", duration: "2 h 30" },
    { block: "Jour 6", theme: "Mini-projet web", duration: "3 h" },
  ],
  targetLevel: [
    "Je sais écrire un SELECT simple.",
    "Je comprends clé primaire et clé étrangère.",
    "Je sais créer une page web structurée.",
    "Je sais réagir à un clic en JavaScript.",
    "Je sais expliquer pourquoi on valide les entrées.",
  ],
  days: week3Collected.days,
  corrections: week3Collected.corrections,
  project: {
    id: "project-week-3",
    title: "Page de révision interactive",
    brief: "Créer une page web qui ajoute des notions à réviser, les compte et explique ses limites de sécurité.",
    requiredFeatures: [
      "Structure HTML claire.",
      "CSS lisible et responsive.",
      "Ajout dynamique d'une notion.",
      "Validation des champs vides.",
      "Compteur de notions.",
    ],
    bonusFeatures: ["Bouton supprimer.", "Filtre par catégorie.", "Sauvegarde localStorage.", "README sécurité."],
    fileStructure: "revision-web/\n├── index.html\n├── style.css\n├── app.js\n└── README.md",
    steps: [
      "Créer la structure HTML.",
      "Ajouter le style de base.",
      "Brancher app.js.",
      "Coder ajout + validation.",
      "Tester et écrire le README.",
    ],
    successCriteria: [
      "La page est lisible.",
      "Le bouton ajoute une notion.",
      "Une saisie vide est refusée.",
      "Le compteur se met à jour.",
      "Les limites sécurité sont expliquées.",
    ],
    grading: [
      { criterion: "HTML", points: 4 },
      { criterion: "CSS", points: 4 },
      { criterion: "DOM", points: 5 },
      { criterion: "Validation", points: 4 },
      { criterion: "README", points: 3 },
    ],
    solution:
      'const input = document.querySelector("#notion");\nconst liste = document.querySelector("#liste");\nconst total = document.querySelector("#total");\nconst erreur = document.querySelector("#erreur");\nlet compteur = 0;\n\ndocument.querySelector("#ajouter").addEventListener("click", () => {\n  const texte = input.value.trim();\n  if (texte === "") {\n    erreur.textContent = "Notion obligatoire";\n    return;\n  }\n  erreur.textContent = "";\n  const li = document.createElement("li");\n  li.textContent = texte;\n  liste.append(li);\n  compteur = compteur + 1;\n  total.textContent = compteur;\n  input.value = "";\n});',
  },
  checkpoint: {
    id: "checkpoint-week-3",
    title: "Bilan semaine 3 - SQL, web et sécurité",
    duration: "1 h 45",
    totalPoints: 100,
    tasks: [
      { id: "w3-cp-sql", block: "SQL", title: "SELECT filtré", points: 20, statement: "Écris une requête qui affiche les étudiants admis triés par moyenne." },
      { id: "w3-cp-join", block: "SQL", title: "Jointure", points: 20, statement: "Explique et écris une jointure étudiants/groupes." },
      { id: "w3-cp-html", block: "Web", title: "Page profil", points: 20, statement: "Crée une page HTML/CSS simple et lisible." },
      { id: "w3-cp-dom", block: "JavaScript", title: "Interaction", points: 25, statement: "Ajoute une notion à une liste via un input et un bouton." },
      { id: "w3-cp-sec", block: "Sécurité", title: "Validation", points: 15, statement: "Explique deux validations et deux secrets à ne pas exposer." },
    ],
    passCriteria: ["70 points ou plus.", "SQL et DOM compris.", "Projet web testé sur mobile."],
    reviewAdvice: [
      { if: "Tu bloques sur SQL", then: "Reprends SELECT/FROM/WHERE avant JOIN." },
      { if: "Tu bloques sur JS", then: "Refais compteur de clics puis input." },
    ],
  },
  sheets: [
    { id: "w3-sheet-sql", title: "SQL minimal", items: ["SELECT colonnes", "FROM table", "WHERE condition", "ORDER BY colonne DESC"] },
    { id: "w3-sheet-web", title: "Web minimal", items: ["HTML structure", "CSS apparence", "JS interaction", "Valider les entrées"] },
  ],
  revisionCards: [
    { id: "w3-card-select", title: "SQL", front: "Quel mot filtre les lignes ?", back: "WHERE.", skill: "sql" },
    { id: "w3-card-dom", title: "DOM", front: "Comment réagir à un clic ?", back: "Avec addEventListener('click', ...).", skill: "dom" },
    { id: "w3-card-sec", title: "Sécurité", front: "Pourquoi ne pas mettre un secret en JS public ?", back: "Parce que le navigateur reçoit et peut lire ce code.", skill: "sécurité" },
  ],
};
